# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac1a430f0df77f607cb05ab2a562b41a0f40b443ce3e3f34d35c0cb7b804938709f0e7e9535746d314feea5a77bc16c5e97282679de067e515bf5619a448202b

test:
  secret_key_base: 0f1b76e3ed1574caf5400c801dda92869d9015a1226058322bdca8af91491acf0d69d970ce352affff75bf61202f097eed8f130962cafa24925f2593ab82ddc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
